# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BL83y_xEbjhcW5n8Zrfm53RrfWbMhBr4

Task 1
"""

num_one = int(input("Enter first no"))
num_two = int(input("Enter second no"))

addition = num_one + num_two
subtration = num_one - num_two
multiplication = num_one * num_two
division = num_one / num_two
print(addition)
print(subtration)
print(multiplication)
print(division)

"""Task 2"""

f_name = str(input("enter your first name"))
l_name = str(input("enter your last name"))

full_name = f_name + " " + l_name
print(f"Hello, {full_name} ! welcome to python programe. ")
